version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: octodevs

    ports:
      - "5432:5432"
    volumes:
      - octodevs:/var/lib/postgressql

volumes:
  octodevs:
